const DATA_MASTER = {
  master: {
    rank: {
      '1': 'Intern',
      '2': 'Employee',
      '3': 'Team Leader',
      '4': 'Head of department',
      '5': 'Director and above',
    },
    skill: {
      '1': 'Excel',
      '2': 'Word',
      '3': 'ERP',
      '4': 'CRM',
      '5': 'Kahoot',
      '6': 'Nearpod',
      '7': 'Flipgrid',
      '8': 'Google Forms',
      '9': 'Rubistar',
      '10': 'Seesaw',
      '11': 'Moodle',
      '12': 'Google Classroom',
      '13': 'Microsoft Teams',
      '14': 'Manufacturing Execution System - MES',
      '15': 'Microsoft Project',
      '16': 'Trello',
      '17': 'Asana',
      '18': 'Confluence',
      '19': 'Pareto Analysis',
      '20': 'Fishbone Diagram',
      '21': 'Control Charts',
      '22': 'Minitab',
      '23': 'Six Sigma',
      '24': 'Quality Companion',
      '25': 'QuickBooks',
      '26': 'SAP',
      '27': 'Oracle Financial',
      '28': 'Misa',
      '29': 'SAPO',
      '30': 'Fast Accounting',
      '31': 'Bravo',
      '32': 'Base',
      '33': 'Salesforce',
      '34': 'HubSpot CRM',
      '35': 'Zoho CRM',
      '36': 'KiotViet',
      '37': 'Sapo',
      '38': 'Misa',
      '39': 'iPOS',
      '40': 'LinkedIn Sales Navigator',
      '41': 'Excel',
      '42': 'Word',
      '43': 'Power BI',
      '44': 'Microsoft Outlook',
      '45': 'Google Ads',
      '46': 'Google Analytics',
      '47': 'Facebook Ads Manager',
      '48': 'Hootsuite',
      '49': 'Yoast SEO',
      '50': 'Email campaign tools',
      '51': 'FastPay HRIS',
      '52': 'Workday',
      '53': 'SAP HCM',
      '54': 'Base.vn',
      '55': '1Office',
      '56': 'MISA',
      '57': 'AMIS',
      '58': 'RiskyDoc',
      '59': 'SafeCare',
      '60': 'RiskMan',
      '61': 'Medisoft',
      '62': 'Vietsoft',
      '63': 'Bkav eDoctor',
      '64': 'Q-Pulse',
      '65': 'MasterControl',
      '66': 'Qualio',
      '67': 'Bash/Shell',
      '68': 'C#',
      '69': 'C/C++',
      '70': 'Go',
      '71': 'HTML/CSS',
      '72': 'Java',
      '73': 'JavaScript',
      '74': 'Kotlin',
      '75': 'PHP',
      '76': 'Python',
      '77': 'Swift',
      '78': 'TypeScript',
      '79': 'Elasticsearch',
      '80': 'Firebase',
      '81': 'DynamoDB',
      '82': 'IBM DB2',
      '83': 'MariaDB',
      '84': 'Microsoft SQL Server',
      '85': 'MongoDB',
      '86': 'MySQL',
      '87': 'Oracle',
      '88': 'PostgreSQL',
      '89': 'Redis',
      '90': 'SQLite',
      '91': 'AWS',
      '92': 'DigitalOcean',
      '93': 'Google Cloud Platform',
      '94': 'Heroku',
      '95': 'IBM Cloud or Watson',
      '96': 'Oracle Cloud Infrastructure',
      '97': 'Microsoft Azure',
      '98': 'Angular',
      '99': 'ASP.NET',
      '100': 'Django',
      '101': 'Drupal',
      '102': 'Express',
      '103': 'Flask',
      '104': 'JQuery',
      '105': 'Laravel',
      '106': 'Magento',
      '107': 'React.js',
      '108': 'Ruby on Rails',
      '109': 'Symfony',
      '110': 'Vue.js',
      '111': '.NET Framework',
      '112': 'Apache Spark',
      '113': 'Cordova',
      '114': 'Flutter',
      '115': 'Hadoop',
      '116': 'Keras',
      '117': 'NumPy',
      '118': 'Pandas',
      '119': 'Torch/PyTorch',
      '120': 'Qt',
      '121': 'TensorFlow',
      '122': 'React Native',
      '123': 'Ansible',
      '124': 'Docker',
      '125': 'Git',
      '126': 'Kubernetes',
      '127': 'Terraform',
      '128': 'Unity 3D',
      '129': 'Xamarin',
      '130': 'Yarn',
      '131': 'MacOS',
      '132': 'Windows Subsystem for Linux (WSL)',
      '133': 'Windows',
      '134': 'Linux',
      '9999': 'Other',
    },
  },
};
